### ISSUE TITLE
Can't resolve `'babel-runtime/regenerator'`

### ISSUE THREAD

**Issue by mukhrr** [notadamking/react-typing-animation#69]
Hi. Even installing this package doesn't help to error to disappear. What can I do? 

![image](https://user-images.githubusercontent.com/71601329/170589109-61c688fe-78ed-4798-b51d-ea48d792bf76.png)

**Comment by zhgrui** [comment]
Are you sure that "npm install babel-runtime" doesn't work? For me, that worked fine

**Comment by mukhrr** [comment]
yeah, it came to work. it was somehow my PC's error, I guess

**Comment by weaversam8** [comment]
This issue should be reopened- if `babel-runtime` is a dependency of this package and it's not getting installed during the first install of `react-typing-animation`, that should be considered a bug.
